## Import dependencies

In [26]:
%matplotlib notebook
# Dependencies declaration

import pandas as pd
from pandas.io import sql
from pandas import DataFrame

import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine

import os

import sqlite3 as lite

## Import all DB catalogs

### Read all the path/names of the catalog files

In [32]:
pwd = os.getcwd()
# print(pwd)

pwd = pwd + '/../resources/raw_DBs/'
# print(pwd)

for path, folders, files in os.walk(pwd):
   ## just rename folders inside path 
    if pwd == path:
#         print(path)
#         print(folders)
        print(files)
if '.DS_Store' in files:
    files.remove('.DS_Store')

['201709-citibike-tripdata.csv', '201809-citibike-tripdata.csv', '2013-09 - Citi Bike trip data.csv', '201701-citibike-tripdata.csv', '201602-citibike-tripdata.csv', '201902-citibike-tripdata.csv', '201512-citibike-tripdata.csv', '201411-citibike-tripdata.csv', '201801-citibike-tripdata.csv', '2014-05 - Citi Bike trip data.csv', '201504-citibike-tripdata.csv', '2014-02 - Citi Bike trip data.csv', '.DS_Store', '201608-citibike-tripdata.csv', '201510-citibike-tripdata.csv', '201803-citibike-tripdata.csv', '201506-citibike-tripdata.csv', '201703-citibike-tripdata.csv', '201610-citibike-tripdata.csv', '201606-citibike-tripdata.csv', '201705-citibike-tripdata.csv', '201805-citibike-tripdata.csv', '201508-citibike-tripdata.csv', '2014-07 - Citi Bike trip data.csv', '201807-citibike-tripdata.csv', '201502-citibike-tripdata.csv', '201811-citibike-tripdata.csv', '2014-08 - Citi Bike trip data.csv', '201711-citibike-tripdata.csv', '201612-citibike-tripdata.csv', '201604-citibike-tripdata.csv', '201707-citibike-tripdata.csv', '201409-citibike-tripdata.csv', '2013-11 - Citi Bike trip data.csv', '201603-citibike-tripdata.csv', '2013-10 - Citi Bike trip data.csv', '201505-citibike-tripdata.csv', '201903-citibike-tripdata.csv', '201410-citibike-tripdata.csv', '201708-citibike-tripdata.csv', '201808-citibike-tripdata.csv', '2014-01 - Citi Bike trip data.csv', '201507-citibike-tripdata.csv', '201511-citibike-tripdata.csv', '2014-06 - Citi Bike trip data.csv', '201901-citibike-tripdata.csv', '201802-citibike-tripdata.csv', '201412-citibike-tripdata.csv', '201702-citibike-tripdata.csv', '201601-citibike-tripdata.csv', '201609-citibike-tripdata.csv', '2013-12 - Citi Bike trip data.csv', '201509-citibike-tripdata.csv', '201607-citibike-tripdata.csv', '201306-citibike-tripdata.csv', '201704-citibike-tripdata.csv', '201712-citibike-tripdata.csv', '201611-citibike-tripdata.csv', '2014-03 - Citi Bike trip data.csv', '201501-citibike-tripdata.csv', '201812-citibike-tripdata.csv', '2013-07 - Citi Bike trip data.csv', '201804-citibike-tripdata.csv', '2014-04 - Citi Bike trip data.csv', '2013-08 - Citi Bike trip data.csv', '201503-citibike-tripdata.csv', '201810-citibike-tripdata.csv', '201806-citibike-tripdata.csv', '201605-citibike-tripdata.csv', '201706-citibike-tripdata.csv', '201710-citibike-tripdata.csv']

In [45]:
print(len(files))

for x in files: 
    print(x)
    print(pwd + x)

df = pd.read_csv(pwd + x, encoding = 'latin1')

70
201709-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201709-citibike-tripdata.csv
201809-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201809-citibike-tripdata.csv
2013-09 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2013-09 - Citi Bike trip data.csv
201701-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201701-citibike-tripdata.csv
201602-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201602-citibike-tripdata.csv
201902-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201902-citibike-tripdata.csv
201512-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201512-citibike-tripdata.csv
201411-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201411-citibike-tripdata.csv
201801-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201801-citibike-tripdata.csv
2014-05 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-05 - Citi Bike trip data.csv
201504-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201504-citibike-tripdata.csv
2014-02 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-02 - Citi Bike trip data.csv
201608-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201608-citibike-tripdata.csv
201510-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201510-citibike-tripdata.csv
201803-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201803-citibike-tripdata.csv
201506-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201506-citibike-tripdata.csv
201703-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201703-citibike-tripdata.csv
201610-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201610-citibike-tripdata.csv
201606-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201606-citibike-tripdata.csv
201705-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201705-citibike-tripdata.csv
201805-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201805-citibike-tripdata.csv
201508-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201508-citibike-tripdata.csv
2014-07 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-07 - Citi Bike trip data.csv
201807-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201807-citibike-tripdata.csv
201502-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201502-citibike-tripdata.csv
201811-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201811-citibike-tripdata.csv
2014-08 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-08 - Citi Bike trip data.csv
201711-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201711-citibike-tripdata.csv
201612-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201612-citibike-tripdata.csv
201604-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201604-citibike-tripdata.csv
201707-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201707-citibike-tripdata.csv
201409-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201409-citibike-tripdata.csv
2013-11 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2013-11 - Citi Bike trip data.csv
201603-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201603-citibike-tripdata.csv
2013-10 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2013-10 - Citi Bike trip data.csv
201505-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201505-citibike-tripdata.csv
201903-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201903-citibike-tripdata.csv
201410-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201410-citibike-tripdata.csv
201708-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201708-citibike-tripdata.csv
201808-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201808-citibike-tripdata.csv
2014-01 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-01 - Citi Bike trip data.csv
201507-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201507-citibike-tripdata.csv
201511-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201511-citibike-tripdata.csv
2014-06 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-06 - Citi Bike trip data.csv
201901-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201901-citibike-tripdata.csv
201802-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201802-citibike-tripdata.csv
201412-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201412-citibike-tripdata.csv
201702-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201702-citibike-tripdata.csv
201601-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201601-citibike-tripdata.csv
201609-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201609-citibike-tripdata.csv
2013-12 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2013-12 - Citi Bike trip data.csv
201509-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201509-citibike-tripdata.csv
201607-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201607-citibike-tripdata.csv
201306-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201306-citibike-tripdata.csv
201704-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201704-citibike-tripdata.csv
201712-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201712-citibike-tripdata.csv
201611-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201611-citibike-tripdata.csv
2014-03 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-03 - Citi Bike trip data.csv
201501-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201501-citibike-tripdata.csv
201812-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201812-citibike-tripdata.csv
2013-07 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2013-07 - Citi Bike trip data.csv
201804-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201804-citibike-tripdata.csv
2014-04 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2014-04 - Citi Bike trip data.csv
2013-08 - Citi Bike trip data.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/2013-08 - Citi Bike trip data.csv
201503-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201503-citibike-tripdata.csv
201810-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201810-citibike-tripdata.csv
201806-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201806-citibike-tripdata.csv
201605-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201605-citibike-tripdata.csv
201706-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201706-citibike-tripdata.csv
201710-citibike-tripdata.csv
/Users/daniel_czz/Desktop/Mundo/Laboral/Educación/Bootcamp/Homeworks/Homework - Week 20/Dashboarding-with-Tableau-and-Python/data_gathering/../resources/raw_DBs/201710-citibike-tripdata.csv

In [46]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,457,2017-10-01 00:00:00,2017-10-01 00:07:38,479,9 Ave & W 45 St,40.760193,-73.991255,478,11 Ave & W 41 St,40.760301,-73.998842,30951,Subscriber,1985.0,1
1,6462,2017-10-01 00:00:20,2017-10-01 01:48:03,279,Peck Slip & Front St,40.707873,-74.001670,307,Canal St & Rutgers St,40.714275,-73.989900,14809,Customer,NaN,0
2,761,2017-10-01 00:00:27,2017-10-01 00:13:09,504,1 Ave & E 16 St,40.732219,-73.981656,350,Clinton St & Grand St,40.715595,-73.987030,28713,Subscriber,1992.0,1
3,1193,2017-10-01 00:00:29,2017-10-01 00:20:22,3236,W 42 St & Dyer Ave,40.758985,-73.993800,3233,E 48 St & 5 Ave,40.757246,-73.978059,16008,Customer,1992.0,2
4,2772,2017-10-01 00:00:32,2017-10-01 00:46:44,2006,Central Park S & 6 Ave,40.765909,-73.976342,469,Broadway & W 53 St,40.763441,-73.982681,14556,Customer,NaN,0

### Connect to the database

In [3]:
path = '../db/'
db_name = 'deaths_inegi.sqlite'

conn = 'sqlite:///' + path + db_name

print(conn)

sqlite:///../db/deaths_inegi.sqlite

In [4]:
database_connection = sqlalchemy.create_engine(conn)

### Read each catalog CSV and load it to the database as a table

In [5]:
print(f'###### Creating the tables')
for x in files:
    try:
        
        if x == 'decateml.csv':
            df = pd.read_csv("resources/catalogos/"+ x, encoding ='latin1')
            s = x.split(".csv")
            df = df.rename(columns={'CVE': str(s[0]) + "_id"})
            df = df.rename(columns={'cve_ent': str(s[0]) + "_entidad_id"})
            df = df.rename(columns={'cve_mun': str(s[0]) + "_municipio_id"})
            df = df.rename(columns={'cve_loc': str(s[0]) + "_locacion_id"})
            df.to_sql("c_"+str(s[0]), con=database_connection, if_exists='replace', index=False) 
        else:
            df = pd.read_csv("resources/catalogos/"+ x, encoding='latin1')
            s = x.split(".csv")
            df = df.rename(columns={'CVE': str(s[0]) + "_id"})
            df.to_sql("c_"+str(s[0]), con=database_connection, if_exists='replace', index=False) 
        
    except Exception as e:
      print(f'Error detected in file', str(e))
    
print(f'###### Tables created')

###### Creating the tables
###### Tables created

In [6]:
# Open and read the file as a single buffer
fd = open('create_db_schema.sql', 'r')
sqlFile = fd.read()
fd.close()

# all SQL commands (split on ';')
sqlCommands = sqlFile.split(';')


try:
    print('[#########] Running the create_db_schema.sql script')
    print(path + db_name)
    conn = lite.connect(path + db_name)
    
    cursor = conn.cursor()
    
    for command in sqlCommands:
        try:
            cursor.execute(command)
            #print(command)
        except Exception as e:
            print(f'Error detected: ', str(e))
            
    print('[#########] create_db_schema.sql script ran succesfuly')
    
except Exception as e:
        print(f'Error detected: ', str(e))
finally:
    #closing database connection.
    conn.close()
    print('[#########] SQL Lite connection is closed')

[#########] Running the create_db_schema.sql script
../db/deaths_inegi.sqlite
[#########] create_db_schema.sql script ran succesfuly
[#########] SQL Lite connection is closed

---

### Load the transactional data into the database

In [7]:
### Se guardan los datos de 10K en 10K en la base de datos
### porque por alguna razon si se meten mas datos el programa crashea
years = ['2012','2013','2014','2015','2016','2017']

for year_str in years:

    d_defunciones_generales = f'defunciones_generales_{year_str}.csv'
    
    print(f'[#########]  Reading {d_defunciones_generales} file.')

    df = pd.read_csv("resources/conjunto_de_datos/"+ d_defunciones_generales, encoding ='latin1')
    
    df['data_year'] = int(year_str)
    

    cargar_de = 10000 

    indexx = 0
    limit = len(df)

    while (indexx<=limit):

        final =  indexx + cargar_de

        try:
            print(f'[#########] Saving from index {indexx} to {final}.')
            df.iloc[indexx:final].to_sql(name='d_defunciones_generales', con=database_connection, if_exists='append', index=False) 

        except Exception as e:
            print(f'Error detected in file', str(e))

        indexx = indexx + cargar_de

    print(f'[#########]  {d_defunciones_generales} data saved.')

[#########]  Reading defunciones_generales_2012.csv file.
[#########] Saving from index 0 to 10000.
[#########] Saving from index 10000 to 20000.
[#########] Saving from index 20000 to 30000.
[#########] Saving from index 30000 to 40000.
[#########] Saving from index 40000 to 50000.
[#########] Saving from index 50000 to 60000.
[#########] Saving from index 60000 to 70000.
[#########] Saving from index 70000 to 80000.
[#########] Saving from index 80000 to 90000.
[#########] Saving from index 90000 to 100000.
[#########] Saving from index 100000 to 110000.
[#########] Saving from index 110000 to 120000.
[#########] Saving from index 120000 to 130000.
[#########] Saving from index 130000 to 140000.
[#########] Saving from index 140000 to 150000.
[#########] Saving from index 150000 to 160000.
[#########] Saving from index 160000 to 170000.
[#########] Saving from index 170000 to 180000.
[#########] Saving from index 180000 to 190000.
[#########] Saving from index 190000 to 200000.
[#########] Saving from index 200000 to 210000.
[#########] Saving from index 210000 to 220000.
[#########] Saving from index 220000 to 230000.
[#########] Saving from index 230000 to 240000.
[#########] Saving from index 240000 to 250000.
[#########] Saving from index 250000 to 260000.
[#########] Saving from index 260000 to 270000.
[#########] Saving from index 270000 to 280000.
[#########] Saving from index 280000 to 290000.
[#########] Saving from index 290000 to 300000.
[#########] Saving from index 300000 to 310000.
[#########] Saving from index 310000 to 320000.
[#########] Saving from index 320000 to 330000.
[#########] Saving from index 330000 to 340000.
[#########] Saving from index 340000 to 350000.
[#########] Saving from index 350000 to 360000.
[#########] Saving from index 360000 to 370000.
[#########] Saving from index 370000 to 380000.
[#########] Saving from index 380000 to 390000.
[#########] Saving from index 390000 to 400000.
[#########] Saving from index 400000 to 410000.
[#########] Saving from index 410000 to 420000.
[#########] Saving from index 420000 to 430000.
[#########] Saving from index 430000 to 440000.
[#########] Saving from index 440000 to 450000.
[#########] Saving from index 450000 to 460000.
[#########] Saving from index 460000 to 470000.
[#########] Saving from index 470000 to 480000.
[#########] Saving from index 480000 to 490000.
[#########] Saving from index 490000 to 500000.
[#########] Saving from index 500000 to 510000.
[#########] Saving from index 510000 to 520000.
[#########] Saving from index 520000 to 530000.
[#########] Saving from index 530000 to 540000.
[#########] Saving from index 540000 to 550000.
[#########] Saving from index 550000 to 560000.
[#########] Saving from index 560000 to 570000.
[#########] Saving from index 570000 to 580000.
[#########] Saving from index 580000 to 590000.
[#########] Saving from index 590000 to 600000.
[#########] Saving from index 600000 to 610000.
[#########]  defunciones_generales_2012.csv data saved.
[#########]  Reading defunciones_generales_2013.csv file.

/anaconda3/envs/PythonData/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (42,50) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

[#########] Saving from index 0 to 10000.
[#########] Saving from index 10000 to 20000.
[#########] Saving from index 20000 to 30000.
[#########] Saving from index 30000 to 40000.
[#########] Saving from index 40000 to 50000.
[#########] Saving from index 50000 to 60000.
[#########] Saving from index 60000 to 70000.
[#########] Saving from index 70000 to 80000.
[#########] Saving from index 80000 to 90000.
[#########] Saving from index 90000 to 100000.
[#########] Saving from index 100000 to 110000.
[#########] Saving from index 110000 to 120000.
[#########] Saving from index 120000 to 130000.
[#########] Saving from index 130000 to 140000.
[#########] Saving from index 140000 to 150000.
[#########] Saving from index 150000 to 160000.
[#########] Saving from index 160000 to 170000.
[#########] Saving from index 170000 to 180000.
[#########] Saving from index 180000 to 190000.
[#########] Saving from index 190000 to 200000.
[#########] Saving from index 200000 to 210000.
[#########] Saving from index 210000 to 220000.
[#########] Saving from index 220000 to 230000.
[#########] Saving from index 230000 to 240000.
[#########] Saving from index 240000 to 250000.
[#########] Saving from index 250000 to 260000.
[#########] Saving from index 260000 to 270000.
[#########] Saving from index 270000 to 280000.
[#########] Saving from index 280000 to 290000.
[#########] Saving from index 290000 to 300000.
[#########] Saving from index 300000 to 310000.
[#########] Saving from index 310000 to 320000.
[#########] Saving from index 320000 to 330000.
[#########] Saving from index 330000 to 340000.
[#########] Saving from index 340000 to 350000.
[#########] Saving from index 350000 to 360000.
[#########] Saving from index 360000 to 370000.
[#########] Saving from index 370000 to 380000.
[#########] Saving from index 380000 to 390000.
[#########] Saving from index 390000 to 400000.
[#########] Saving from index 400000 to 410000.
[#########] Saving from index 410000 to 420000.
[#########] Saving from index 420000 to 430000.
[#########] Saving from index 430000 to 440000.
[#########] Saving from index 440000 to 450000.
[#########] Saving from index 450000 to 460000.
[#########] Saving from index 460000 to 470000.
[#########] Saving from index 470000 to 480000.
[#########] Saving from index 480000 to 490000.
[#########] Saving from index 490000 to 500000.
[#########] Saving from index 500000 to 510000.
[#########] Saving from index 510000 to 520000.
[#########] Saving from index 520000 to 530000.
[#########] Saving from index 530000 to 540000.
[#########] Saving from index 540000 to 550000.
[#########] Saving from index 550000 to 560000.
[#########] Saving from index 560000 to 570000.
[#########] Saving from index 570000 to 580000.
[#########] Saving from index 580000 to 590000.
[#########] Saving from index 590000 to 600000.
[#########] Saving from index 600000 to 610000.
[#########] Saving from index 610000 to 620000.
[#########] Saving from index 620000 to 630000.
[#########]  defunciones_generales_2013.csv data saved.
[#########]  Reading defunciones_generales_2014.csv file.
[#########] Saving from index 0 to 10000.
[#########] Saving from index 10000 to 20000.
[#########] Saving from index 20000 to 30000.
[#########] Saving from index 30000 to 40000.
[#########] Saving from index 40000 to 50000.
[#########] Saving from index 50000 to 60000.
[#########] Saving from index 60000 to 70000.
[#########] Saving from index 70000 to 80000.
[#########] Saving from index 80000 to 90000.
[#########] Saving from index 90000 to 100000.
[#########] Saving from index 100000 to 110000.
[#########] Saving from index 110000 to 120000.
[#########] Saving from index 120000 to 130000.
[#########] Saving from index 130000 to 140000.
[#########] Saving from index 140000 to 150000.
[#########] Saving from index 150000 to 160000.
[#########] Saving from index 160000 to 170000.
[#########] Saving from index 170000 to 180000.
[#########] Saving from index 180000 to 190000.
[#########] Saving from index 190000 to 200000.
[#########] Saving from index 200000 to 210000.
[#########] Saving from index 210000 to 220000.
[#########] Saving from index 220000 to 230000.
[#########] Saving from index 230000 to 240000.
[#########] Saving from index 240000 to 250000.
[#########] Saving from index 250000 to 260000.
[#########] Saving from index 260000 to 270000.
[#########] Saving from index 270000 to 280000.
[#########] Saving from index 280000 to 290000.
[#########] Saving from index 290000 to 300000.
[#########] Saving from index 300000 to 310000.
[#########] Saving from index 310000 to 320000.
[#########] Saving from index 320000 to 330000.
[#########] Saving from index 330000 to 340000.
[#########] Saving from index 340000 to 350000.
[#########] Saving from index 350000 to 360000.
[#########] Saving from index 360000 to 370000.
[#########] Saving from index 370000 to 380000.
[#########] Saving from index 380000 to 390000.
[#########] Saving from index 390000 to 400000.
[#########] Saving from index 400000 to 410000.
[#########] Saving from index 410000 to 420000.
[#########] Saving from index 420000 to 430000.
[#########] Saving from index 430000 to 440000.
[#########] Saving from index 440000 to 450000.
[#########] Saving from index 450000 to 460000.
[#########] Saving from index 460000 to 470000.
[#########] Saving from index 470000 to 480000.
[#########] Saving from index 480000 to 490000.
[#########] Saving from index 490000 to 500000.
[#########] Saving from index 500000 to 510000.
[#########] Saving from index 510000 to 520000.
[#########] Saving from index 520000 to 530000.
[#########] Saving from index 530000 to 540000.
[#########] Saving from index 540000 to 550000.
[#########] Saving from index 550000 to 560000.
[#########] Saving from index 560000 to 570000.
[#########] Saving from index 570000 to 580000.
[#########] Saving from index 580000 to 590000.
[#########] Saving from index 590000 to 600000.
[#########] Saving from index 600000 to 610000.
[#########] Saving from index 610000 to 620000.
[#########] Saving from index 620000 to 630000.
[#########] Saving from index 630000 to 640000.
[#########]  defunciones_generales_2014.csv data saved.
[#########]  Reading defunciones_generales_2015.csv file.
[#########] Saving from index 0 to 10000.
[#########] Saving from index 10000 to 20000.
[#########] Saving from index 20000 to 30000.
[#########] Saving from index 30000 to 40000.
[#########] Saving from index 40000 to 50000.
[#########] Saving from index 50000 to 60000.
[#########] Saving from index 60000 to 70000.
[#########] Saving from index 70000 to 80000.
[#########] Saving from index 80000 to 90000.
[#########] Saving from index 90000 to 100000.
[#########] Saving from index 100000 to 110000.
[#########] Saving from index 110000 to 120000.
[#########] Saving from index 120000 to 130000.
[#########] Saving from index 130000 to 140000.
[#########] Saving from index 140000 to 150000.
[#########] Saving from index 150000 to 160000.
[#########] Saving from index 160000 to 170000.
[#########] Saving from index 170000 to 180000.
[#########] Saving from index 180000 to 190000.
[#########] Saving from index 190000 to 200000.
[#########] Saving from index 200000 to 210000.
[#########] Saving from index 210000 to 220000.
[#########] Saving from index 220000 to 230000.
[#########] Saving from index 230000 to 240000.
[#########] Saving from index 240000 to 250000.
[#########] Saving from index 250000 to 260000.
[#########] Saving from index 260000 to 270000.
[#########] Saving from index 270000 to 280000.
[#########] Saving from index 280000 to 290000.
[#########] Saving from index 290000 to 300000.
[#########] Saving from index 300000 to 310000.
[#########] Saving from index 310000 to 320000.
[#########] Saving from index 320000 to 330000.
[#########] Saving from index 330000 to 340000.
[#########] Saving from index 340000 to 350000.
[#########] Saving from index 350000 to 360000.
[#########] Saving from index 360000 to 370000.
[#########] Saving from index 370000 to 380000.
[#########] Saving from index 380000 to 390000.
[#########] Saving from index 390000 to 400000.
[#########] Saving from index 400000 to 410000.

[#########] Saving from index 410000 to 420000.
[#########] Saving from index 420000 to 430000.
[#########] Saving from index 430000 to 440000.
[#########] Saving from index 440000 to 450000.
[#########] Saving from index 450000 to 460000.
[#########] Saving from index 460000 to 470000.
[#########] Saving from index 470000 to 480000.
[#########] Saving from index 480000 to 490000.
[#########] Saving from index 490000 to 500000.
[#########] Saving from index 500000 to 510000.
[#########] Saving from index 510000 to 520000.
[#########] Saving from index 520000 to 530000.
[#########] Saving from index 530000 to 540000.
[#########] Saving from index 540000 to 550000.
[#########] Saving from index 550000 to 560000.
[#########] Saving from index 560000 to 570000.
[#########] Saving from index 570000 to 580000.
[#########] Saving from index 580000 to 590000.
[#########] Saving from index 590000 to 600000.
[#########] Saving from index 600000 to 610000.
[#########] Saving from index 610000 to 620000.
[#########] Saving from index 620000 to 630000.
[#########] Saving from index 630000 to 640000.
[#########] Saving from index 640000 to 650000.
[#########] Saving from index 650000 to 660000.
[#########]  defunciones_generales_2015.csv data saved.
[#########]  Reading defunciones_generales_2016.csv file.
[#########] Saving from index 0 to 10000.
[#########] Saving from index 10000 to 20000.
[#########] Saving from index 20000 to 30000.
[#########] Saving from index 30000 to 40000.
[#########] Saving from index 40000 to 50000.
[#########] Saving from index 50000 to 60000.
[#########] Saving from index 60000 to 70000.
[#########] Saving from index 70000 to 80000.
[#########] Saving from index 80000 to 90000.
[#########] Saving from index 90000 to 100000.
[#########] Saving from index 100000 to 110000.
[#########] Saving from index 110000 to 120000.
[#########] Saving from index 120000 to 130000.
[#########] Saving from index 130000 to 140000.
[#########] Saving from index 140000 to 150000.
[#########] Saving from index 150000 to 160000.
[#########] Saving from index 160000 to 170000.
[#########] Saving from index 170000 to 180000.
[#########] Saving from index 180000 to 190000.
[#########] Saving from index 190000 to 200000.
[#########] Saving from index 200000 to 210000.
[#########] Saving from index 210000 to 220000.
[#########] Saving from index 220000 to 230000.
[#########] Saving from index 230000 to 240000.
[#########] Saving from index 240000 to 250000.
[#########] Saving from index 250000 to 260000.
[#########] Saving from index 260000 to 270000.
[#########] Saving from index 270000 to 280000.
[#########] Saving from index 280000 to 290000.
[#########] Saving from index 290000 to 300000.
[#########] Saving from index 300000 to 310000.
[#########] Saving from index 310000 to 320000.
[#########] Saving from index 320000 to 330000.
[#########] Saving from index 330000 to 340000.
[#########] Saving from index 340000 to 350000.
[#########] Saving from index 350000 to 360000.
[#########] Saving from index 360000 to 370000.
[#########] Saving from index 370000 to 380000.
[#########] Saving from index 380000 to 390000.
[#########] Saving from index 390000 to 400000.
[#########] Saving from index 400000 to 410000.
[#########] Saving from index 410000 to 420000.
[#########] Saving from index 420000 to 430000.
[#########] Saving from index 430000 to 440000.
[#########] Saving from index 440000 to 450000.
[#########] Saving from index 450000 to 460000.
[#########] Saving from index 460000 to 470000.
[#########] Saving from index 470000 to 480000.
[#########] Saving from index 480000 to 490000.
[#########] Saving from index 490000 to 500000.
[#########] Saving from index 500000 to 510000.
[#########] Saving from index 510000 to 520000.
[#########] Saving from index 520000 to 530000.
[#########] Saving from index 530000 to 540000.
[#########] Saving from index 540000 to 550000.
[#########] Saving from index 550000 to 560000.
[#########] Saving from index 560000 to 570000.
[#########] Saving from index 570000 to 580000.
[#########] Saving from index 580000 to 590000.
[#########] Saving from index 590000 to 600000.
[#########] Saving from index 600000 to 610000.
[#########] Saving from index 610000 to 620000.
[#########] Saving from index 620000 to 630000.
[#########] Saving from index 630000 to 640000.
[#########] Saving from index 640000 to 650000.
[#########] Saving from index 650000 to 660000.
[#########] Saving from index 660000 to 670000.
[#########] Saving from index 670000 to 680000.
[#########] Saving from index 680000 to 690000.
[#########]  defunciones_generales_2016.csv data saved.
[#########]  Reading defunciones_generales_2017.csv file.
[#########] Saving from index 0 to 10000.
[#########] Saving from index 10000 to 20000.
[#########] Saving from index 20000 to 30000.
[#########] Saving from index 30000 to 40000.
[#########] Saving from index 40000 to 50000.
[#########] Saving from index 50000 to 60000.
[#########] Saving from index 60000 to 70000.
[#########] Saving from index 70000 to 80000.
[#########] Saving from index 80000 to 90000.
[#########] Saving from index 90000 to 100000.
[#########] Saving from index 100000 to 110000.
[#########] Saving from index 110000 to 120000.
[#########] Saving from index 120000 to 130000.
[#########] Saving from index 130000 to 140000.
[#########] Saving from index 140000 to 150000.
[#########] Saving from index 150000 to 160000.
[#########] Saving from index 160000 to 170000.
[#########] Saving from index 170000 to 180000.
[#########] Saving from index 180000 to 190000.
[#########] Saving from index 190000 to 200000.
[#########] Saving from index 200000 to 210000.
[#########] Saving from index 210000 to 220000.
[#########] Saving from index 220000 to 230000.
[#########] Saving from index 230000 to 240000.
[#########] Saving from index 240000 to 250000.
[#########] Saving from index 250000 to 260000.
[#########] Saving from index 260000 to 270000.
[#########] Saving from index 270000 to 280000.
[#########] Saving from index 280000 to 290000.
[#########] Saving from index 290000 to 300000.
[#########] Saving from index 300000 to 310000.
[#########] Saving from index 310000 to 320000.
[#########] Saving from index 320000 to 330000.
[#########] Saving from index 330000 to 340000.
[#########] Saving from index 340000 to 350000.
[#########] Saving from index 350000 to 360000.
[#########] Saving from index 360000 to 370000.
[#########] Saving from index 370000 to 380000.
[#########] Saving from index 380000 to 390000.
[#########] Saving from index 390000 to 400000.
[#########] Saving from index 400000 to 410000.
[#########] Saving from index 410000 to 420000.
[#########] Saving from index 420000 to 430000.
[#########] Saving from index 430000 to 440000.
[#########] Saving from index 440000 to 450000.
[#########] Saving from index 450000 to 460000.
[#########] Saving from index 460000 to 470000.
[#########] Saving from index 470000 to 480000.
[#########] Saving from index 480000 to 490000.
[#########] Saving from index 490000 to 500000.
[#########] Saving from index 500000 to 510000.
[#########] Saving from index 510000 to 520000.
[#########] Saving from index 520000 to 530000.
[#########] Saving from index 530000 to 540000.
[#########] Saving from index 540000 to 550000.
[#########] Saving from index 550000 to 560000.
[#########] Saving from index 560000 to 570000.
[#########] Saving from index 570000 to 580000.
[#########] Saving from index 580000 to 590000.
[#########] Saving from index 590000 to 600000.
[#########] Saving from index 600000 to 610000.
[#########] Saving from index 610000 to 620000.
[#########] Saving from index 620000 to 630000.
[#########] Saving from index 630000 to 640000.
[#########] Saving from index 640000 to 650000.
[#########] Saving from index 650000 to 660000.
[#########] Saving from index 660000 to 670000.
[#########] Saving from index 670000 to 680000.
[#########] Saving from index 680000 to 690000.
[#########] Saving from index 690000 to 700000.
[#########] Saving from index 700000 to 710000.
[#########]  defunciones_generales_2017.csv data saved.

In [8]:

try:
    print("[#########] Reading table")
    
    print(path + db_name)
    conn = lite.connect(path + db_name)

    cursor = conn.cursor()

    sql_select_Query = "select * from vw_derecho_habiencia;"

    cursor.execute(sql_select_Query)

    result_df = DataFrame(cursor.fetchall())
    table_desc = cursor.description

    headers = []
    for header in table_desc:
        headers.append(header[0])

    result_df.columns = headers

    #for row in records:
    #    print(row)

    cursor.close()
    
    print("[#########] Table saved to dataframe")

except Exception as e:
    print(f'Error detected in file', str(e))
finally:
    #closing database connection.
    conn.close()
    print("[#########] SQLite connection is closed")

[#########] Reading table
../db/deaths_inegi.sqlite
[#########] Table saved to dataframe
[#########] SQLite connection is closed

In [9]:
result_df

    data_year  derechohab                 derechi_habiencia  cantidad_derecho
0        2012           1                           Ninguna            121871
1        2012           2                              IMSS            198974
2        2012           3                            ISSSTE             43519
3        2012           4                             PEMEX              5009
4        2012           5                            SEDENA              3363
5        2012           6                             SEMAR               963
6        2012           7                    Seguro popular            142357
7        2012           8                              Otra             12380
8        2012           9                IMSS oportunidades              3386
9        2012          99  Derechohabiencia no especificada             70532
10       2013           1                           Ninguna            120911
11       2013           2                              IMSS            208527
12       2013           3                            ISSSTE             45430
13       2013           4                             PEMEX              5306
14       2013           5                            SEDENA              3690
15       2013           6                             SEMAR              1040
16       2013           7                    Seguro popular            153377
17       2013           8                              Otra             12161
18       2013           9                IMSS oportunidades              3863
19       2013          99  Derechohabiencia no especificada             69294
20       2014           1                           Ninguna            114155
21       2014           2                              IMSS            212059
22       2014           3                            ISSSTE             46247
23       2014           4                             PEMEX              5338
24       2014           5                            SEDENA              3601
25       2014           6                             SEMAR              1046
26       2014           7                    Seguro popular            166168
27       2014           8                              Otra             12627
28       2014           9                IMSS oportunidades              3499
29       2014          99  Derechohabiencia no especificada             68901
30       2015           1                           Ninguna            112636
31       2015           2                              IMSS            218069
32       2015           3                            ISSSTE             47395
33       2015           4                             PEMEX              5401
34       2015           5                            SEDENA              3684
35       2015           6                             SEMAR              1236
36       2015           7                    Seguro popular            178069
37       2015           8                              Otra             12965
38       2015           9                IMSS oportunidades              3241
39       2015          99  Derechohabiencia no especificada             72992
40       2016           1                           Ninguna            115677
41       2016           2                              IMSS            228360
42       2016           3                            ISSSTE             50284
43       2016           4                             PEMEX              5656
44       2016           5                            SEDENA              3901
45       2016           6                             SEMAR              1253
46       2016           7                    Seguro popular            187747
47       2016           8                              Otra             13505
48       2016           9                IMSS oportunidades              2896
49       2016          99  Derechohabiencia no especificada             76487
50       2017           1                           Ninguna            113464
51       2017           2                              IMSS            234382
52       2017           3                            ISSSTE             52297
53       2017           4                             PEMEX              5602
54       2017           5                            SEDENA              3994
55       2017           6                             SEMAR              1240
56       2017           7                    Seguro popular            190194
57       2017           8                              Otra             13719
58       2017           9                IMSS oportunidades              2741
59       2017          99  Derechohabiencia no especificada             85414